final Map<String, List<String>> interestCategories = {
  'Personality': [
    'Cold',
    'Dominance',
    'Care',
    'Possessiveness',
    'Helpless',
    'Hate You',
    'Quiet/Shy',
    'Bully',
    'Secretly Loves You',
    'Crazy',
    'Rude',
    'Dependent',
    'Contrast',
    'Submissive',
    'Your Crush',
    'Mature',
    'Flirty',
    'Lust',
    'Tsundere',
  ],
  'Relationship': [
    'Schoolmate',
    'Villain',
    'Husband',
    'Stranger',
    'Sibling',
    'Cousin',
    'Lover',
    'Roommate',
    'Enemy',
    'Tough Guy',
    'Boss',
    'Non-Human',
    'Friend',
    'Childhood Friend',
    'Ex',
    'Celebrity',
    'Father',
    'Servant',
    'Wife',
    'Teacher',
    'Mother',
    'Neighbor',
  ],
  'Scene': [
    'Indoor',
    'School',
    'Get in Trouble',
    'Fantasy',
    'Multi-character',
    'Forced Marriage',
    'Marriage',
    'Restriction of Movement',
    'Rainy',
    'Narrow Space',
    'Betray',
    'Public',
    'Revenge',
    'Force Love',
    'Reunion',
    'Ex',
    'Celebrity',
    'Father',
    'Servant',
    'Wife',
    'Teacher',
    'Mother',
    'Neighbor',
  ],
};
