// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP5qWEOLCw22UXEGErF_Ls_QztDLKw504',
    appId: '1:898756982960:web:6aeb029269e2a94a512375',
    messagingSenderId: '898756982960',
    projectId: 'yoome-ai-b03cf',
    authDomain: 'yoome-ai-b03cf.firebaseapp.com',
    storageBucket: 'yoome-ai-b03cf.firebasestorage.app',
    measurementId: 'G-ZB5G428D8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASS6HjhrTc7TgIJCcBHa7aggXuV6S_ZdI',
    appId: '1:898756982960:android:f1bf90eba27d4207512375',
    messagingSenderId: '898756982960',
    projectId: 'yoome-ai-b03cf',
    storageBucket: 'yoome-ai-b03cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXDR131ZInqe7tN3XXEHX4im1N39AVp2c',
    appId: '1:898756982960:ios:029ab8bcc215ba70512375',
    messagingSenderId: '898756982960',
    projectId: 'yoome-ai-b03cf',
    storageBucket: 'yoome-ai-b03cf.firebasestorage.app',
    iosBundleId: 'com.example.yoomeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXDR131ZInqe7tN3XXEHX4im1N39AVp2c',
    appId: '1:898756982960:ios:029ab8bcc215ba70512375',
    messagingSenderId: '898756982960',
    projectId: 'yoome-ai-b03cf',
    storageBucket: 'yoome-ai-b03cf.firebasestorage.app',
    iosBundleId: 'com.example.yoomeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP5qWEOLCw22UXEGErF_Ls_QztDLKw504',
    appId: '1:898756982960:web:47d0332ec521a8d5512375',
    messagingSenderId: '898756982960',
    projectId: 'yoome-ai-b03cf',
    authDomain: 'yoome-ai-b03cf.firebaseapp.com',
    storageBucket: 'yoome-ai-b03cf.firebasestorage.app',
    measurementId: 'G-DWV4X0ZCS9',
  );
}
