// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABzZjwjlclq8qUw9YccDAx760Sk7XK1ow',
    appId: '1:353818779194:web:0db7199e82c6a86dc05f03',
    messagingSenderId: '353818779194',
    projectId: 'yoome-ai',
    authDomain: 'yoome-ai.firebaseapp.com',
    storageBucket: 'yoome-ai.firebasestorage.app',
    measurementId: 'G-Z02WT8FLL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5AdIj0X0zXp1cHVIkB3HfOaSQo_VM17w',
    appId: '1:353818779194:android:08b8a89c04ffb1f9c05f03',
    messagingSenderId: '353818779194',
    projectId: 'yoome-ai',
    storageBucket: 'yoome-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdnTIKe0penzOHhoQlL0Rze9Db4cccR-0',
    appId: '1:353818779194:ios:4db278fc50576c9bc05f03',
    messagingSenderId: '353818779194',
    projectId: 'yoome-ai',
    storageBucket: 'yoome-ai.firebasestorage.app',
    iosBundleId: 'com.example.yoomeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdnTIKe0penzOHhoQlL0Rze9Db4cccR-0',
    appId: '1:353818779194:ios:4db278fc50576c9bc05f03',
    messagingSenderId: '353818779194',
    projectId: 'yoome-ai',
    storageBucket: 'yoome-ai.firebasestorage.app',
    iosBundleId: 'com.example.yoomeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABzZjwjlclq8qUw9YccDAx760Sk7XK1ow',
    appId: '1:353818779194:web:88a9f0a7e881c739c05f03',
    messagingSenderId: '353818779194',
    projectId: 'yoome-ai',
    authDomain: 'yoome-ai.firebaseapp.com',
    storageBucket: 'yoome-ai.firebasestorage.app',
    measurementId: 'G-SHWPBNBTXY',
  );
}
